executable            = TEMPL_TASKDIR/conf/run.sh
input                 = TEMPL_TASKDIR/conf/params.sh
arguments             = $(ClusterID) $(ProcId)
output                = TEMPL_TASKDIR/logs/job.$(ClusterId).$(ProcId).out
error                 = TEMPL_TASKDIR/logs/job.$(ClusterId).$(ProcId).err
log                   = TEMPL_TASKDIR/logs/condor.$(ClusterId).log
+JobFlavour           = "TEMPL_JOBFLAVOR"
queue TEMPL_NJOBS
